name: Build Windows main executable

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build_windows.yaml"
      - "**.c"
      - "**.h"
      - "**.hpp"
      - "**.cpp"
      - "**.cmake"
      - "**.patch"
      - "**.ico"
      - "**.rc"
      - "**.json"
      - "**.hpp.in"
      - "**.py"
      - "**/CMakeLists.txt"
  repository_dispatch:
    types: [ update ]

jobs:
  build_windows_x86:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare
        run: |
          mkdir cmake-build-x86
          mkdir cmake-build-x64
          mkdir dist

      - name: Build x86 Shipping
        run: |
          cd cmake-build-x86
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 17 2022" -A "Win32"
          cmake -–build . -j
          copy src/v2/RelWithDebInfo/LuaSTGPlus2.exe ../dist/LuaSTGPlus2_x86.exe

      - name: Build x86 Development
        run: |
          cd cmake-build-x86
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 17 2022" -A "Win32" -DLSTG_SHIPPING=OFF
          cmake -–build . -j
          copy src/v2/RelWithDebInfo/LuaSTGPlus2.exe ../dist/LuaSTGPlus2_x86.dev.exe

      - name: Build x64 Shipping
        run: |
          cd cmake-build-x64
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 17 2022" -A "x64"
          cmake -–build . -j
          copy src/v2/RelWithDebInfo/LuaSTGPlus2.exe ../dist/LuaSTGPlus2_x64.exe

      - name: Build x64 Development
        run: |
          cd cmake-build-x64
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Visual Studio 17 2022" -A "x64" -DLSTG_SHIPPING=OFF
          cmake -–build . -j
          copy src/v2/RelWithDebInfo/LuaSTGPlus2.exe ../dist/LuaSTGPlus2_x64.dev.exe

      - uses: actions/upload-artifact@v3
        with:
          name: LuaSTGPlus2-${{ github.sha }}
          path: |
            build/dist/*.exe
