name: Build Windows

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build_windows.yaml"
      - "**.c"
      - "**.h"
      - "**.hpp"
      - "**.cpp"
      - "**.cmake"
      - "**.patch"
      - "**.ico"
      - "**.rc"
      - "**.json"
      - "**.hpp.in"
      - "**.py"
      - "**/CMakeLists.txt"
  repository_dispatch:
    types: [ update ]

jobs:
  build_windows:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare
        run: |
          mkdir cmake-build-x64
          mkdir dist

      - name: Build x64 Shipping
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64
          cd cmake-build-x64
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Ninja"
          ninja -j 3

      - name: Copy build output
        run: |
          copy cmake-build-x64\src\v2\LuaSTGPlus2.exe dist\LuaSTGPlus2.exe

      - name: Build x64 Development
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" x64
          cd cmake-build-x64
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Ninja" -DLSTG_SHIPPING=OFF
          ninja -j 3

      - name: Copy build output
        run: |
          copy cmake-build-x64\src\v2\LuaSTGPlus2.exe dist\LuaSTGPlus2.dev.exe

      - uses: actions/upload-artifact@v3
        with:
          name: LuaSTGPlus2-${{ github.sha }}
          path: |
            build/dist/*.exe
