name: Build Documents

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build_doc.yaml"
      - "doc/**.md"
      - "doc/**.svg"
      - "doc/**.png"
      - "doc/package.json"
  repository_dispatch:
    types: [ update ]

jobs:
  build_doc:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      # Switch to nodejs
      - name: Switch nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
      - name: Build static pages
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          cd doc
          yarn install
          yarn run build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: LuaSTG/LuaSTG.github.io
          publish_dir: ./doc/src/.vuepress/dist
          publish_branch: master
          cname: luastg.com
